name: Maven Release
# GitHub Actions cannot run the whole release procedure.
# Releases are initiated by running a script on developer machine, which then triggers this workflow via REST API.
on:
  repository_dispatch:
    types: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Java Setup
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    # We would prefer actions/setup-java to also setup GPG signing for us, but that feature is not yet available.
    - name: Import GPG Key
      run: |
        mkdir -p ~/.gnupg/
        printf "$MAVEN_SIGNING_KEY" | base64 --decode > ~/.gnupg/maven-signing-key.gpg
        gpg --import ~/.gnupg/maven-signing-key.gpg
      env:
        MAVEN_SIGNING_KEY: ${{ secrets.MAVEN_SIGNING_KEY }}
    - name: Maven Deploy
      # Printing maven version (-V) helps diagnose GitHub-specific build behavior.
      run: mvn -B -V deploy
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

